from typing import Protocol

from fastkit_cache.provider.health import CacheHealth


class CacheProvider(Protocol):
    async def get(self, key: str) -> bytes | None: ...

    async def set(self, key: str, value: bytes, ttl: int | None = None) -> None: ...

    async def delete(self, key: str) -> None: ...

    async def delete_many(self, keys: list[str]) -> None: ...

    async def exists(self, key: str) -> bool: ...

    async def touch(self, key: str, ttl: int) -> None: ...

    async def increment(
        self, key: str, amount: int = 1, ttl: int | None = None
    ) -> int: ...

    async def clear_namespace(self, namespace: str) -> None: ...

    async def health(self) -> CacheHealth: ...
