from typing import Protocol

from fastkit_storage.provider.health import StorageHealth
from fastkit_storage.provider.object_stat import ObjectStat
from fastkit_storage.provider.presigned_url import PresignedUrl


class StorageProvider(Protocol):
    async def put(
        self, key: str, data: bytes, content_type: str | None = None
    ) -> ObjectStat: ...

    async def get(self, key: str) -> bytes: ...

    async def delete(self, key: str) -> None: ...

    async def exists(self, key: str) -> bool: ...

    async def stat(self, key: str) -> ObjectStat: ...

    async def copy(self, source: str, destination: str) -> None: ...

    async def move(self, source: str, destination: str) -> None: ...

    async def presign_upload(
        self, key: str, expires_in: int = 3600
    ) -> PresignedUrl: ...

    async def presign_download(
        self, key: str, expires_in: int = 3600
    ) -> PresignedUrl: ...

    async def health(self) -> StorageHealth: ...
